### ISSUE TITLE
请教，如何在微服务框架中，获取用户登录信息？

### ISSUE THREAD

**Issue by YoChen** [WilliamXu96/ABP-MicroService#1]
基于多租戶的环境，前端用VUE搭建时，如何获取用户登录信息，目前是直接下载的最新版的ABP微服务示例。我没有在示例中找到js的api授权方式，接口中也未找到。

**Comment by WilliamXu96** [comment]
@YoChen  前端登录需要在ABP微服务示例的授权服务中获取token，将token保存至cookie或者缓存中请求ABP接口时携带就可以了，这两篇文章有介绍Vue Element Admin接入ABP授权的过程
https://www.cnblogs.com/william-xu/p/11249800.html
https://www.cnblogs.com/william-xu/p/11274431.html

**Comment by YoChen** [comment]
非常感谢您的回答，请问这几个接口，是自己写的吗？我在默认示例中没有找到这些服务
/user/userLogin
/connect/token
/connect/userinfo

另外，我通过你的链接，发现有两个不同的源码仓库地址，请问他们有什么不同吗？我下载使用的是以下第一个源码。
1、https://github.com/abpframework/abp
2、https://github.com/aspnetboilerplate/aspnetboilerplate

**Comment by YoChen** [comment]
不好意思，初接触ABP,还有很多在摸索中，在统一用户认证中心找到可以使用connet/token这些接口，但目前在获取Token的时候出现错误，数据库中可以看到有记录，请问是怎么回事呢？
![image](https://user-images.githubusercontent.com/1983996/79324529-55aa1380-7f42-11ea-88db-d4747b82e90f.png)
![image](https://user-images.githubusercontent.com/1983996/79324576-65295c80-7f42-11ea-99fd-c278ec715c41.png)

**Comment by WilliamXu96** [comment]
> 不好意思，初接触ABP,还有很多在摸索中，在统一用户认证中心找到可以使用connet/token这些接口，但目前在获取Token的时候出现错误，数据库中可以看到有记录，请问是怎么回事呢？
> ![image](https://user-images.githubusercontent.com/1983996/79324529-55aa1380-7f42-11ea-88db-d4747b82e90f.png)
> ![image](https://user-images.githubusercontent.com/1983996/79324576-65295c80-7f42-11ea-99fd-c278ec715c41.png)

![image](https://user-images.githubusercontent.com/44634687/79324975-fb5d8280-7f42-11ea-8ff1-0e7cedf376df.png)
授权类型使用password
@YoChen

**Comment by YoChen** [comment]
依然是一样的未获取到token
![image](https://user-images.githubusercontent.com/1983996/79326358-509a9380-7f45-11ea-90ad-8c6dc2c02c24.png)
我在数据库中[IdentityServerClientGrantTypes]表看到的对应clientid的[GrantType]为hybrid。

**Comment by YoChen** [comment]
感谢您的解答，或许是我添加了一个默认租户，并去掉了博客服务导致的，我再仔细检查一下，并把abp框架的源码下载到本地来调试跟踪一下，现在是直接nuget的abp已经编译好的dll，所以看不到是什么情况。

**Comment by WilliamXu96** [comment]
> 依然是一样的未获取到token
> ![image](https://user-images.githubusercontent.com/1983996/79326358-509a9380-7f45-11ea-90ad-8c6dc2c02c24.png)
> 我在数据库中[IdentityServerClientGrantTypes]表看到的对应clientid的[GrantType]为hybrid。

client_secret是明文，换成1q2w3e*试下
@YoChen

**Comment by YoChen** [comment]
目前还是没有测试成功通过。也没找到如何加断点，请问/connect/token 这个接口的实现具体在哪个位置？@WilliamXu96

**Comment by litiansky** [comment]
@YoChen 我前几天已经调通了 默认示例种子里面要用app那个去登陆就可以

**Comment by YoChen** [comment]
谢谢，我在授权中增加了password方式，然后再用明文1q2w3e*作为secret，就可以了，感谢您的解答。个人觉得应该在管理员界面中，增加Auth授权配置这些功能。
