### ISSUE TITLE
数据源切换到 Mysql 报错

### ISSUE THREAD

**Issue by yosheng** [WilliamXu96/ABP-MicroService#12]
Business.Host 引用 Volo.Abp.EntityFrameworkCore.MySQL 可以切换到 Mysql 数据库
进行 Migration Add 正常，使用 Database Update 后会出现下述错误

>  MySQL server version for the right syntax to use near 'MAX) NULL,

反编译后发现问题在 引用自 XCZ.EntityFrameworkCore 命名空间中出现指定生成字段代码如下
```cs
        b.Property<string>((Expression<Func<FormField, string>>) (x => x.Regx)).HasColumnType<string>("nvarchar(MAX)");
        b.Property<string>((Expression<Func<FormField, string>>) (x => x.Options)).HasColumnType<string>("nvarchar(MAX)");
```

这里应该可以不强置指定 默认就会生成 longtext 而 sql server 也可以正常生成 nvarchar(MAX) 不知道是否可以稍做调整？
因为我找不到  XCZ.EntityFrameworkCore 原码也无法提交PR 😅

**Comment by WilliamXu96** [comment]
@yosheng 收到，感谢指出，稍后调整。form-management计划开发成插件服务，所以代码暂未发布。
