### ISSUE TITLE
系统管理【除“角色管理”】相关模块数据无法加载，提示未找到服务

### ISSUE THREAD

**Issue by billzhuh** [WilliamXu96/ABP-MicroService#15]
点击系统管理相关模块功能提示无法找到服务（角色管理可正常加载数据）

**Comment by WilliamXu96** [comment]
@billzhuh 确定所有服务都启动成功，严格按照启动示例操作：https://www.cnblogs.com/william-xu/p/12806810.html

**Comment by billzhuh** [comment]
AuthServer.Host   BaseService.Host   Business.Host   FileStorage.Host   WebAppGateway.Host

WebApp\vue

一共五个服务和一个vue前端，通过批处理脚本均正常启动；也尝试过将五个服务直接在vs中启动；  但是登陆成功后在系统管理中相关模块无法加载【除角色管理】；  用户能成功登陆所以至少系统管理--用户管理  理论上应该是正常，但是前端却提示“无法找到服务”

补充：我使用得mysql，且相关迁移执行成功

**Comment by WilliamXu96** [comment]
@billzhuh 暂未遇到类似反馈，请更新代码或者排查相关配置及环境

**Comment by dotnba** [comment]
体验地址报错，500 Internal Privoxy Error
