### ISSUE TITLE
想问下如果在centos上部署微服务，一般会用什么数据库

### ISSUE THREAD

**Issue by niufwshd** [WilliamXu96/ABP-MicroService#22]
非常感谢你的好文章，微服务的代码也在我本地运行良好。我看到你的ci/cd是在linux上，就想到服务可能都会在linux上运行。如果是windows上的使用sql server，部署到centos上据说sql server至少要真用2G内存，很好资源。在实际的项目中大神会选用什么数据库，sql server？mysql？postgesql？。请给出一些提示，谢谢！

**Comment by WilliamXu96** [comment]
@niufwshd 多台服务器的话单独的mssql比较好，单台建议postgesql

**Comment by niufwshd** [comment]
非常感谢!
