### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by ZerekZhang** [WilliamXu96/ABP-MicroService#26]
1、当前权限管理太过于集中，框架依赖于IPermissionDefinitionProvider，如果要管理权限，则Admin模块必须依赖于权限配置模块，如果权限越来越多，很难有效的管理（查询权限也会越来越慢）
2、在前端（VUE-Element-admin）如何动态的获取权限（页面模块及模块按钮）
![image](https://user-images.githubusercontent.com/16829343/106721580-c93b1f80-663f-11eb-8bc8-e22aba758188.png)
 前端开发人员是不知道具体的权限的（v-permission 的 值 前端人员不知道），所以才有了此问题
3、在多租户情况下，手机端如何在不提供租户输入框的情况下，服务层如何获取租户问题？
4、AuthServer.Host 集成了ID4 还是希望有AdminUI 界面（系统 ^_^）
---
学习abp 时间不长，望解答！ 谢谢！

**Comment by WilliamXu96** [comment]
@AjuPrince 团队项目文档很重要，前后端都需要有文档可供参考，abp目前只能确认租户后登录，abp商业版提供了ids4管理界面

**Comment by ZerekZhang** [comment]
@WilliamXu96 感谢解答！我深入了解下后再做深入交流
