### ISSUE TITLE
appsettings.json中有一个AllowedHosts,是如何使用的？

### ISSUE THREAD

**Issue by YoChen** [WilliamXu96/ABP-MicroService#3]
疑惑？这个不是跨域的设置么？我看你的项目中单独增加了一个CorsOrigins，不能是直接用AllowedHosts:* 这样的写法吗？即允许所有接口跨域？

**Comment by WilliamXu96** [comment]
@YoChen 目前使用的是CorsOrigins配置，AllowedHosts是以前使用的没有删除

**Comment by YoChen** [comment]
在网关上设置了跨域，微服务中就不用设置垮域了吗？因为webapp是直接请求的网关中的接口？

**Comment by WilliamXu96** [comment]
> 在网关上设置了跨域，微服务中就不用设置垮域了吗？因为webapp是直接请求的网关中的接口？

@YoChen 
是的，只有授权服务和网关服务需要配置允许跨域，其他微服务不需要

**Comment by YoChen** [comment]
如果我的客户端是桌面应用程序（WPF开发的），如何在这里设置跨域呢，我请求接口用的Refit，好像是直接new的一个HttpClient来请求的。

**Comment by WilliamXu96** [comment]
HttpClient直接调用接口不存在跨域 @YoChen
