### ISSUE TITLE
vue安装依赖时总会在下面这个地方报错 这个时需要翻墙吗？

### ISSUE THREAD

**Issue by yanhong2008** [WilliamXu96/ABP-MicroService#50]
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/adobe-webplatform/eve.git/': OpenSSL SSL_read: Connection was reset, errno 10054
npm ERR!
npm ERR! exited with error code: 128

**Comment by WilliamXu96** [comment]
关闭git ssl验证
git config --global http.sslVerify "false"
@yanhong2008

**Comment by yanhong2008** [comment]
> 关闭git ssl验证 git config --global http.sslVerify "false" @yanhong2008
关闭后  仍报这个错  还有其它什么要点吗？

deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Error while executing:
npm ERR! D:\SoftInstall\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/adobe-webplatform/eve.git/': Failed to connect to github.com port 443: Timed out
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-08-12T05_38_04_237Z-debug.log
